### ISSUE TITLE
[Send left, centre, right to EKF]

### ISSUE THREAD

**Issue by ErikRowe** [vortexntnu/deprecated-vortex-cv#24]
**Time estimate:** 3 hours  
**Deadline:**  28.jan

**Description of task:**
Create function that finds the leftmost, centremost and rightmost 3D-points in a detection. Send these points as a message with OBJECT ID and the points as an array with fixed positions.

**Comment by theBadMusician** [comment]
Closing this, as we are gonna be using quaternions instead.
