### ISSUE TITLE
Find a way to calibrate the extrinsic parameters of a stereo camera (Camera Calibration)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#28]
**Time estimate:** 15 hours  (150 hours)
**Deadline:**  N/A

**Description of task:**
For some reason, the ROS calibration package that we were using, did not work at the pool. Because of its unreliability, another solution should be found and tested (tested so we know it works on multiple PCs, and preferably, offline – with a set of left/right images). One suggestion is the calibration package from OpenCV, [https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html](https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html).

**Comment by theBadMusician** [comment]
Reference to the previous calibration issue in Vortex-AUV: [https://github.com/vortexntnu/Vortex-AUV/issues/283](https://github.com/vortexntnu/Vortex-AUV/issues/283). It has relevant info on the ROS calibration package.

**Comment by theBadMusician** [comment]
Link to a useful issue from the zed-ros-wrapper repo, which goes into how the stereo calibration params are calculated in the ZED SDK: [https://github.com/stereolabs/zed-ros-wrapper/issues/39](https://github.com/stereolabs/zed-ros-wrapper/issues/39)

**Comment by KristianSem** [comment]
https://github.com/magnarok49/TTK4255/blob/master/camera_calibration.py

**Comment by Bruglen** [comment]
So we have managed to use code that finds the intrinsic parameters. We will now look into finding the extrinsic parameters by using OpenCV's stereo calibration function.

**Comment by theBadMusician** [comment]
Closing, as we got satisfactory calibration params using Matlab calib toolbox.
