### ISSUE TITLE
Implement and test the object pose estimation EKF (Vision-EKF)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#34]
**Time estimate:** 20 hours  
**Deadline:**  07.02.22

**Description of task:**
Find and squash the bugs that give the invalid results from the EKF node, and finish implementing the vision-pose estimation filter. As the problem is very likely related to frames being used in the simulator and/or one of the conformed transformation matrices, it is important to test the node using the rosbags taken at the MC-lab.

**Comment by theBadMusician** [comment]
[Issue 294 in Vortex-AUV](https://github.com/vortexntnu/Vortex-AUV/issues/294) - reference to the original object EKF issue.

**Comment by ivangushkov** [comment]
Some pointers and specifications for the code:
- Use as many ready made tf commands as possible. Make the code as agnostic as possible to frames.
- Map out where we cannot use standard tf commands and have to make a rotational object ourselves and minimize the instances of those (only do it when absolutely necessary)
- Evaluate the actual need for "transform_to_world" (can we do everything cleanly with tf commands?)
- Consider the switch to quaternion parametrization after the ekf works on the bags

**Comment by ivangushkov** [comment]
The simulation on bag data:
0) Start with only position.
1) Generate and publish measurements of the gate (transform gt pose topic from qualsys to camera frame).
2) Feed the measurements to the filter along with drone pose from.
3) Publish the estimate in QualSys frame again to check if it converges on gt. This is not ideal, but it is better than trying to transform between odom and QualSys. We should just make sure that the middle part of the code works, regardless of what frame comes in and out.

**Comment by ivangushkov** [comment]
The simulations were performed successfully on sunday  06.02.2022. What we found out and where the problems stemmed from:
- Using tf for all transformations always. Don't try to implement rotations in any way yourself.
- When one needs a rotation matrix from the quaternion provided by transformation use tf.transformations.quaternion_matrix( q ). This has a lot less ambiguity than euler angles.
- The tf lookup function, when called on a parent and child frame gives the rotation from child to parent (we believe)

The EKF node was further rewritten to be quite blind to whatever transformations come into the system and should be more robust for that kind of stuff. 
![image](https://user-images.githubusercontent.com/69768720/152686190-fc60400b-9960-4859-b84d-dbbbb3800737.png)

**Comment by ivangushkov** [comment]
Estimation of the full 6 DOF pose of an object in the world frame is now the focus of the development here. In the period 13-18 february analytic expressions for the measurement model and its jacobian were derived through SymPy and implemented with njit for faster run times. Here is a glimpse into jacobian
![Screenshot from 2022-02-16 18-18-02](https://user-images.githubusercontent.com/69768720/154752294-ff91e875-38b0-4732-8887-82fb8b97abc6.png)
 hell:

**Comment by ivangushkov** [comment]
The focus from now is to implement this into ROS and as a measurement model in the ekf measurementmodels.py script.

TODO for 20.02.2022:

- [x] Implement the njit-ed function with ROS (make a self instance on startup of the ekf node and just pass it into ekf  spørsmålstegn x3 )
- [x] Extend the measurement model to include the new states and jacobian
- [x] Test everything with published full gate pose like we did for position and debugg.

**Comment by ivangushkov** [comment]
The focus from now is to implement this into ROS and as a measurement model in the ekf measurementmodels.py script.

TODO for 20.02.2022:

- [ ] Implement the njit-ed function with ROS (make a self instance on startup of the ekf node and just pass it into ekf  spørsmålstegn x3 )
- [ ] Extend the measurement model to include the new states and jacobian
- [ ] Test everything with published full gate pose like we did for position and debugg.

**Comment by ivangushkov** [comment]
This can safely be closed now. The VKF's newest incarnation has all of these issues pretty much irrelevant.
