### ISSUE TITLE
Orientation Solution Implementation (Vision-EKF)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#42]
Position estimation in the Vision-EKF is fully implemented and working, but the orientation estimates diverges at some points in the runtime. The orientation model Jacobian has been calculated using SimuPy, and is a massive 3x3 matrix, which is incedibly hard to debug.

**Comment by ivangushkov** [comment]
Sucess was had when the measurement was transformed to world frame and the complicated measurement model and ugly Jacobian was foregone in that way. The filter estimates orientation now, however there is something weird with the transformation we are getting to world. Need to look into that and debug it.

![image](https://user-images.githubusercontent.com/69768720/155297871-fa1a3247-bef5-4acb-a81b-d2860113f16f.png)

**Comment by ivangushkov** [comment]
This can safely be closed now. The issue of fixing the orientation is mostly handled, and taken up in newer issues.
