### ISSUE TITLE
Use the Matlab calibration package to get the extrinsic calib params (Camera Calibration)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#46]
**Time estimate:** 20 hours 

**Description of task:**
Test the calibration package found in Matlab, and see if it possible to calibrate both, the intrinsic and the extrinsic, camera parameters using it. It is a good idea to test this on a Linux version so that we know it can be done with the computers present at the office.

**Comment by Bruglen** [comment]
We have managed to use matlab in order to go through camera calibration. We get both intrinsics and extrinsics. However we need to test how good the extrinsics are.

**Comment by KristianSem** [comment]
Calibrating the intrinsic beforehand and utilizing these, generates more accurate extrinsic than doing an all in one intrinsic and extrinsic calibration. The steroCameraCalibrator requires fixed intrinsic parameters in the structure that the cameraCalibrator (single camera) exports its values in (a struct). But values are still of by quite alot in comparison with the true values.

All in one result:
![extrinsic_params_ZY](https://user-images.githubusercontent.com/56901056/156916478-8546365d-aa05-415b-93d2-ae703dc18a60.png)

Pre calibrated intrinsics:
![20pairs_extrinsic](https://user-images.githubusercontent.com/56901056/156917278-3b94b95c-9c39-4408-81c8-27f0e144fb06.png)



The calibration steps were inspired by the research paper from [Vision based obstacle avoidance and motion tracking for autonomous behaviors in underwater vehicles](https://ieeexplore.ieee.org/document/8084619)

**Comment by KristianSem** [comment]
Remeber that the intrinsic parameters are in the shape for matlab:  
![image](https://user-images.githubusercontent.com/56901056/156923889-c170a9f1-ec34-4b05-97eb-c1af633a97bb.png)

**Comment by theBadMusician** [comment]
Closing this, as we got satisfactory params.
