### ISSUE TITLE
Transform computed pose into the world frame (Pointcloud Processing)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#49]
**Time estimate:** 10 hours

**Description of task:**
The Vision-EKF needs object poses in the odom (world) frame to be able to function properly. The output from the pointcloud processing node needs to be transformed from the local camera frame into the world frame. The complete TF is going to be a complex of both static and dynamic TFs.

**Comment by ivangushkov** [comment]
This is implemented and works mostly fine. One thing to look into is why we get different orientation output from the VKF. A possible explanation might be how the quaternion is handled in the VKF, as the VKF assumes w is the last element of quaternion array. I will look into that during this week. Time estimate: 1 hr

**Comment by theBadMusician** [comment]
Closing, as this is implemented.
