### ISSUE TITLE
Calibration testing (Camera Calibration)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#56]
**Time estimate:** 3 hours 

**Description of task:**
- Tune extrinsic parameters using matlab with fixed intrinsic parameters
- test the new parameters on rosbags
- compare opencv with matlab

**Comment by KristianSem** [comment]
For the next pool test we should get some more angles of the calibration board, aswell as pictures taking in slower motion. This may result in a more accurate extrinsic parameters calibration.

**Comment by theBadMusician** [comment]
Calibration works for intrinsic parameters.
