### ISSUE TITLE
 CLAHE and GW (Image Preprocessing)

### ISSUE THREAD

**Issue by theBadMusician** [vortexntnu/deprecated-vortex-cv#58]
**Time estimate:** 10 hours
**Description of task:**
Write a ROS node that takes in raw RGB data from the ZED camera, and pre-processes it using Contrast Limited Adaptive Histogram Equalization (CLAHE) and Gray-World (GW). Apply the pre-processing on RGB data, as well as a chosen colour channel, e.g. R-channel.

**Comment by ivangushkov** [comment]
We have now implemented:
CLAHE
Gray World on a single image

Possible ToDo:

- [ ] Gray world on a batch of images. Should be built in conjunction with a more sophisticated object search/converge strategy. Example: drone swims slowly forward, stops and takes a batch of images, the images are used to compute batch GW parameters, then we apply to the image and search for object. (possibly 1-2 hours on Perception side, more on auto)
- [ ] DAGW properly implemented with optimization. (possibly 2-3 hours)

**Comment by theBadMusician** [comment]
Closing this, as GW and CLAHE is implemented. We may open a separate issue for DAGW at a later date.
